language: node_js
node_js:
  - '11.7.0'
install:
  - npm install -g codecov
script:
  - codecov
cache:
  yarn: true
jobs:
  include:
    - stage: test
      script:
        - npm test
        - codecov
