language: node_js
node_js:
  - 'node'
cache:
  yarn: true
github-token: SUNBEAM-DEPLOY
jobs:
  include:
    - stage: test
      script: npm test a
    - stage: deploy
      if: type = push AND branch = master
      script: npm run deploy
