language: node_js
node_js:
  - 'node'
cache:
  yarn: true
jobs:
  include:
    - stage: test
      script: npm test a
    - stage: deploy
      if: type = push AND branch = master
      skip-cleanup: true
      github-token: $SUNBEAM_DEPLOY
      keep-history: true
      script: npm run deploy
