language: node_js
node_js:
  - 'node'
cache:
  yarn: true
github-token: SUNBEAM-DEPLOY
jobs:
  include:
    - script: npm test a
    - if: type = push AND branch = master
      - script: npm run deploy
