language: node_js
node_js:
  - 'node'
cache:
  yarn: true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $SUNBEAM_DEPLOY
  keep-history: true
  on:
    branch: master
jobs:
  include:
    - stage: test
      script: npm test a
    - stage: deploy
      if: type = push AND branch = master
      script:
        - git config --global user.email "dev.gavin.li@gmail.com"
        - npm run deploy
